### PR TITLE
Frank/#14_Validations_for_step_1_multi_form_signup

### PR DESCRIPTION
**Pull request by MaxiFrancis**

### CODE REVIEW

**Comment by ghefraim** [comment]
Is this branch based on `frank/#14_PersonalDetailsForm` or `main`?

**Comment by ghefraim** [comment]
> > Is this branch based on `frank/#14_PersonalDetailsForm` or `main`?
> 
> Yes.

I'm assuming Yes for the first one. I'm changing the base branch for the PR. 

This way, we will only review the difference between **this branch** `frank/ValidationsForStep1_MultiFormSignup` and the _other feature branch_ `frank/#14_PersonalDetailsForm`. 

Please keep **this branch** updated with the _other feature branch_.

When we complete the PR, **this branch** goes first into the _other feature branch_, and then the _other feature branch_ goes into `main`. 

I hope it's not confusing:D

**Comment by MaxiFrancis** [comment]
> > > Is this branch based on `frank/#14_PersonalDetailsForm` or `main`?
> > 
> > 
> > Yes.
> 
> I'm assuming Yes for the first one. I'm changing the base branch for the PR.
> 
> This way, in this PR, we will only review the difference between **this branch** `frank/ValidationsForStep1_MultiFormSignup` and the _other feature branch_ `frank/#14_PersonalDetailsForm`.
> 
> Please keep **this branch** updated with the _other feature branch_.
> 
> When we complete the PR, **this branch** goes first into the _other feature branch_, and then the _other feature branch_ goes into `main`.
> 
> I hope it's not confusing:D

Yes I wanted to do the same firstly.
But Idk, I forgot when creating the PR.

You can do it, and this may have some changes that fix the comments on the previous PR.

**Comment by MaxiFrancis** [comment]
Ah, I remember, I did create the PR to merge directly to main because I thought that this is not part of the multiFormSignup personal info functionality. So I did not wanted to merge them.

**Comment by ghefraim** [comment]
Ok, but when you created it, I think you based it on the other feature branch. See the file differences is higher versus main:

image

image

**Comment by ghefraim** [comment]
I propose we merge the other branch to main first.

Then we take care of this one.

**Comment by ghefraim** [comment]
Now we can move further with this one. Please fix merge conflicts

**Review by ghefraim — CHANGES_REQUESTED** [review]
Please fix merge issues

**Review by ghefraim — APPROVED** [review]

**Pull request merged**
