### PR TITLE
Index page - added text content and small layout changes

### PR DESCRIPTION
**Pull request by DenisWithOneN**

### CODE REVIEW

**Review by ghefraim — CHANGES_REQUESTED** [review]

**Review by ghefraim — APPROVED** [review]

**Review by ghefraim — CHANGES_REQUESTED** [review]
Images are not visible. Please adjust the urls in the code as well

You can set them to "assets/images/..."

**Comment by DenisWithOneN** [comment]
We should be set for deploy, managed to incorporate all the changes

**Comment by ghefraim** [comment]
The gallery section is empty on the deployed version
https://deploy-preview-83--hopecamp.netlify.app/
image

**Comment by ghefraim** [comment]
Yea pls change the relative paths of the static items to absolute. This should fix the bug i was seeing

**Comment by DenisWithOneN** [comment]
> Yea pls change the relative paths of the static items to absolute. This should fix the bug i was seeing

image

I got this warning when using the base relative path and changed it (from public/assets to ./assets). Worked fine in the local development so I didn't see the issue, but apparently it wasn't right for deployment. Changed it now to /assets it should be good for deploy

**Review by ghefraim — APPROVED** [review]

**Pull request merged**
