### PR TITLE
[Register] Change alert with an UI error component #30

### PR DESCRIPTION
**Pull request by MaxiFrancis**

### CODE REVIEW

**Comment by ghefraim** [comment]
This is still in "work in progress", right?

**Comment by MaxiFrancis** [comment]
> This is still in "work in progress", right?

No. I consider the error component done.
I slit the ticket and created another ticket for the loading component.

**Comment by ghefraim** [comment]
The loading component - has been done in another PR in the meantime by me. Sorry for not communicating that

**Comment by ghefraim** [comment]
As per the error component, this is not quite what i was referring to. The error component shouldnt replace the input validation errors, but rather take care of unexpected errors such as user auth/creation errors

**Comment by ghefraim** [comment]
Please have another look, and if there's still issues i can take this ticket and give you another one if you're available. Thanks

**Comment by MaxiFrancis** [comment]
Ah, yes, now I see what are you reffering too.

**Review by ghefraim — APPROVED** [review]
the code was good. made some adjustments. thanks.

**Pull request merged**
